#!/bin/bash

echo "🚀 Quick Deployment Guide"
echo "=========================="
echo ""
echo "Your app is ready! Here's how to deploy (choose ONE method):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 1: Render (Recommended - Free Forever)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Create GitHub repo"
echo "  • Go to: https://github.com/new"
echo "  • Name it: financial-portfolio"
echo "  • Make it PUBLIC"
echo "  • Don't add README or .gitignore"
echo "  • Click 'Create repository'"
echo ""
echo "Step 2: Push your code"
echo "  cd /home/asvanth/Pictures/financial-portfolio"
echo "  git remote add origin https://github.com/Asvanthc/financial-portfolio.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "Step 3: Deploy on Render"
echo "  • Go to: https://dashboard.render.com/"
echo "  • Click 'New +' → 'Web Service'"
echo "  • Connect your GitHub repo"
echo "  • Everything is auto-configured via render.yaml"
echo "  • Select 'Free' instance"
echo "  • Click 'Create Web Service'"
echo "  • Wait 2-3 minutes"
echo "  • Done! 🎉"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 2: Railway (Also Free - Even Simpler)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Go to: https://railway.app/"
echo "  2. Click 'Start a New Project'"
echo "  3. Select 'Deploy from GitHub repo'"
echo "  4. Connect your repo (or create one first)"
echo "  5. Railway auto-detects and deploys"
echo "  6. Done in 1 minute! 🚀"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 3: Cyclic (Simplest - No Config Needed)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Go to: https://app.cyclic.sh/"
echo "  2. Click 'Connect a GitHub Repo'"
echo "  3. Select your repo"
echo "  4. Click 'Connect Cyclic'"
echo "  5. Instant deployment! ⚡"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Notes:"
echo "  • All services have free tiers"
echo "  • Your app will be live 24/7"
echo "  • Free tier may sleep after inactivity (wakes in ~30s)"
echo "  • No credit card needed for any of them"
echo ""
echo "🎯 Current directory: /home/asvanth/Pictures/financial-portfolio"
echo "📦 Production build: Already completed in portfolio-app/dist/"
echo "✅ Ready to deploy!"
echo ""
